Web/SportsForum.Web/Areas/Administration/Controllers/CategoriesController.cs
namespace SportsForum.Web.Areas.Administration.Controllers
{
    using System.Linq;
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Mvc;
    using Microsoft.EntityFrameworkCore;
    using SportsForum.Data.Common.Repositories;
    using SportsForum.Data.Models;

    [Area("Administration")]
    public class CategoriesController : Controller
    {
        private readonly IDeletableEntityRepository<Category> categoryRepository;

        public CategoriesController(IDeletableEntityRepository<Category> categoryRepository)
        {
            this.categoryRepository = categoryRepository;
        }

        public async Task<IActionResult> Index()
        {
            return this.View(await this.categoryRepository.All().ToListAsync());
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return this.NotFound();
            }

            var category = await this.categoryRepository.All().FirstOrDefaultAsync(m => m.Id == id);
            if (category == null)
            {
                return this.NotFound();
            }

            return this.View(category);
        }

        public IActionResult Create()
        {
            return this.View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Name,Title,Description,ImageUrl,IsDeleted,DeletedOn,Id,CreatedOn,ModifiedOn")] Category category)
        {
            if (this.ModelState.IsValid)
            {
                await this.categoryRepository.AddAsync(category);
                await this.categoryRepository.SaveChangesAsync();
                return this.RedirectToAction(nameof(this.Index));
            }

            return this.View(category);
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return this.NotFound();
            }

            var category = await this.categoryRepository.All().FirstAsync(x => x.Id == id);
            if (category == null)
            {
                return this.NotFound();
            }

            return this.View(category);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Name,Title,Description,ImageUrl,IsDeleted,DeletedOn,Id,CreatedOn,ModifiedOn")] Category category)
        {
            if (id != category.Id)
            {
                return this.NotFound();
            }

            if (this.ModelState.IsValid)
            {
                try
                {
                    this.categoryRepository.Update(category);
                    await this.categoryRepository.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!this.CategoryExists(category.Id))
                    {
                        return this.NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }

                return this.RedirectToAction(nameof(this.Index));
            }

            return this.View(category);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return this.NotFound();
            }

            var category = await this.categoryRepository.All()
                .FirstOrDefaultAsync(m => m.Id == id);
            if (category == null)
            {
                return this.NotFound();
            }

            return this.View(category);
        }


        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var category = await this.categoryRepository.All().FirstAsync(x => x.Id == id);
            this.categoryRepository.Delete(category);
            await this.categoryRepository.SaveChangesAsync();
            return this.RedirectToAction(nameof(this.Index));
        }

        private bool CategoryExists(int id)
        {
            return this.categoryRepository.All().Any(e => e.Id == id);
        }
    }
}

Web/SportsForum.Web/Controllers/CategoriesController.cs
namespace SportsForum.Web.Controllers
{
    using System;

    using Microsoft.AspNetCore.Mvc;
    using SportsForum.Services.Data;
    using SportsForum.Web.ViewModels.Categories;
    using SportsForum.Web.ViewModels.Posts;

    public class CategoriesController : BaseController
    {
        private const int ItemsPerPage = 5;

        private readonly ICategoriesService categoryService;
        private readonly IPostsService postsService;

        public CategoriesController(ICategoriesService categoryService, IPostsService postsService)
        {
            this.categoryService = categoryService;
            this.postsService = postsService;
        }

        public IActionResult ByName(string name, int page = 1)
        {
            if (page <= 0)
            {
                return this.NotFound();
            }

            var viewModel = this.categoryService.GetByName<CategoryViewModel>(name);

            if (viewModel == null)
            {
                return this.NotFound();
            }

            viewModel.ForumPosts =
                this.postsService.GetByCategoryId<PostInCategoryViewModel>(viewModel.Id, ItemsPerPage, (page - 1) * ItemsPerPage);

            viewModel.CurrentPage = page;
            viewModel.ItemsPerPage = ItemsPerPage;
            viewModel.PostsCount = this.postsService.GetCountByCategoryId(viewModel.Id);
            viewModel.PagesCount = (int)Math.Ceiling((double)viewModel.PostsCount / ItemsPerPage);

            if (viewModel.PagesCount == 0)
            {
                viewModel.PagesCount = 1;
            }

            return this.View(viewModel);
        }
    }
}

Web/SportsForum.Web/Controllers/PostsController.cs
namespace SportsForum.Web.Controllers
{
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using SportsForum.Data.Models;
    using SportsForum.Services.Data;
    using SportsForum.Web.ViewModels.Categories;
    using SportsForum.Web.ViewModels.Posts;

    public class PostsController : BaseController
    {
        private readonly IPostsService postsService;
        private readonly ICategoriesService categoriesService;
        private readonly UserManager<ApplicationUser> userManager;

        public PostsController(IPostsService postsService, ICategoriesService categoriesService, UserManager<ApplicationUser> userManager)
        {
            this.postsService = postsService;
            this.categoriesService = categoriesService;
            this.userManager = userManager;
        }

        [HttpGet]
        [Authorize]
        public IActionResult Create()
        {
            var model = new PostCreateInputModel()
            {
                Categories = this.categoriesService.GetCategories<CategoryDropDownViewModel>(),
            };

            return this.View(model);
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Create(PostCreateInputModel postInput)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(postInput);
            }

            var userId = this.userManager.GetUserId(this.User);
            var postId = await this.postsService.CreatePostAsync(postInput, userId);

            return this.RedirectToAction(nameof(this.ById), new { id = postId });
        }

        [HttpGet]
        public IActionResult ById(int id)
        {
            var postViewModel = this.postsService.GetById<PostViewModel>(id);

            if (postViewModel == null)
            {
                return this.NotFound();
            }

            return this.View(postViewModel);
        }
    }
}

Web/SportsForum.Web/Views/Categories/ByName.cshtml
@using SportsForum.Common
@model SportsForum.Web.ViewModels.Categories.CategoryViewModel
@{
    this.ViewData["Title"] = Model.Title;
}

<h1 class="display-3">@Model.Title</h1>
<br />
<div class="alert alert-info">
    @Model.Description
</div>

@foreach (var post in Model.ForumPosts)
{
    <div class="card">
        <div class="card-body">
            <div class="media-body">
                <h4 class="media-heading"><a asp-controller="Posts" asp-action="ById" asp-route-id="@post.Id">@post.Title</a></h4>
                <p>@post.ShortDescription</p>
                <ul class="list-inline list-unstyled text-right">
                    <li class="list-inline-item">
                        <i class="fas fa-user-edit"></i> @post.UserUserName
                    </li>
                    <li class="list-inline-item">
                        <i class="fas fa-calendar-alt"></i> @post.CreatedOn
                    </li>
                    <li class="list-inline-item">
                        <i class="fas fa-comment-dots"></i> @post.CommentsCount comments
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <br />
}

<nav aria-label="...">
    <ul class="pagination justify-content-center">
        @if (this.Model.CurrentPage <= 1)
        {
            <li class="page-item disabled">
                <a class="page-link" href="#">Previous</a>
            </li>
        }
        else
        {
            <li class="page-item">
                <a class="page-link"
                   asp-route="forumCategory"
                   asp-route-name="@this.Model.Title"
                   asp-route-page="@(this.Model.CurrentPage - 1)">Previous</a>
            </li>
        }

        @for (int i = 1; i <= this.Model.PagesCount; i++)
        {
            var active = i == this.Model.CurrentPage ? "active" : string.Empty;
            <li class="page-item @active">
                <a class="page-link"
                   asp-route="forumCategory"
                   asp-route-name="@this.Model.Title"
                   asp-route-page="@i">@i</a>
            </li>
        }

        @if (this.Model.CurrentPage == this.Model.PagesCount || this.Model.CurrentPage == 0)
        {
            <li class="page-item disabled">
                <a class="page-link" href="#">Next</a>
            </li>
        }
        else
        {
            <li class="page-item">
                <a class="page-link"
                   asp-route="forumCategory"
                   asp-route-name="@this.Model.Title"
                   asp-route-page="@(this.Model.CurrentPage + 1)">Next</a>
            </li>
        }
    </ul>
</nav>